### ISSUE TITLE
Refactor form IDs out of class attributes

### ISSUE THREAD

**Issue by bowensanders** [MetaMask/test-snaps#42]
per rekmarks:
we should refactor the test-snaps page to use the`id="..."` tag attribute rather than `class="..."`
this may have an impact on e2e tests so we may want to bundle this change with the test-snaps redesign pull #40

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/test-snaps/42?planning-poker) with ZenHub @bowensanders @FrederikBolding @Mrtenz @ritave @GuillaumeRx @hmalik88

**Comment by FrederikBolding** [comment]
Fixed in #40
